from typing import Any, Dict, List, Tuple
import re


OSCILLOSCOPE_EXPERIMENT_ID = "exp_oscilloscope"
OSCILLOSCOPE_FIRST_SLOT_ID = "IMG_RAW_DATA"
OSCILLOSCOPE_FIRST_SLOT_TABLE_HINT = {
    "t": "正弦波",
    "f": ["T(ms)", "拍周期(ms)", "f1= Hz", "f2= Hz"],
}


def _text(value: Any) -> str:
    return str(value or "").strip()


def _compact(value: Any, max_len: int = 80) -> str:
    text = re.sub(r"\s+", " ", _text(value))
    return text[:max_len]


_UNIT_PATTERN = re.compile(
    r"(?:单位|标准单位|10\^-?\d+|10[⁻-]?\d+|"
    r"KPa|kPa|Pa|mV|V|kHz|MHz|Hz|ms|mm|cm|nm|kg|Kg|g|A|μA|uA|Ω|℃|°C|%|J|S|s|m)"
)


def _strip_unit_text(value: Any) -> str:
    text = _compact(value, 40)
    if not text:
        return ""
    text = re.sub(
        r"（[^）]*(?:单位|标准单位|KPa|kPa|Pa|mV|V|kHz|MHz|Hz|ms|mm|cm|nm|kg|Kg|g|A|μA|uA|Ω|℃|°C|%|J|S)[^）]*）",
        "",
        text,
    )
    text = re.sub(
        r"\([^)]*(?:单位|标准单位|KPa|kPa|Pa|mV|V|kHz|MHz|Hz|ms|mm|cm|nm|kg|Kg|g|A|μA|uA|Ω|℃|°C|%|J|S)[^)]*\)",
        "",
        text,
    )
    text = re.sub(
        r"[/／]\s*(?:10\^-?\d+\s*)?(?:KPa|kPa|Pa|mV|V|kHz|MHz|Hz|ms|mm|cm|nm|kg|Kg|g|A|μA|uA|Ω|℃|°C|%|J|S|s|m)\b",
        "",
        text,
    )
    text = re.sub(r"(?<=\d)(?:KPa|kPa|Pa|mV|V|kHz|MHz|Hz|ms|mm|cm|nm|kg|Kg|g|A|μA|uA|Ω|℃|°C|%|J|S|s|m)(?![A-Za-z])", "", text)
    text = re.sub(r"\s+", "", text)
    if not text or text in {"单位", "标准单位"} or _UNIT_PATTERN.fullmatch(text):
        return ""
    return text[:24]


def _append_unique(items: List[str], value: Any, limit: int = 16) -> None:
    text = _strip_unit_text(value)
    if text and text not in items and len(items) < limit:
        items.append(text)


def _format_candidate_lines(candidates: List[Dict[str, Any]]) -> str:
    lines = []
    for exp in candidates:
        name = _compact(exp.get("name"), 80)
        if name:
            lines.append(name)
        for slot in exp.get("slots") or []:
            slot_id = slot.get("candidateId")
            if slot.get("tables"):
                lines.append(f"- {slot_id}")
                for table in (slot.get("tables") or [])[:6]:
                    title = table.get("t") or "表格"
                    fields = "、".join(table.get("f") or [])
                    lines.append(f"  {title}：{fields}" if fields else f"  {title}")
            else:
                label = slot.get("label") or "图片槽"
                lines.append(f"- {slot_id}：{label}")
    return "\n".join(lines)


def _computed_asset_slot_ids(exp_config: Dict[str, Any]) -> set:
    slot_ids = set()
    computed_assets = exp_config.get("computedAssets") or {}
    assets = computed_assets.values() if isinstance(computed_assets, dict) else computed_assets
    for asset in assets or []:
        if isinstance(asset, dict) and asset.get("imageSlotId"):
            slot_ids.add(str(asset.get("imageSlotId")))
    return slot_ids


def is_user_upload_image_slot(slot: Dict[str, Any], exp_config: Dict[str, Any]) -> bool:
    slot_id = _text(slot.get("id"))
    if not slot_id:
        return False
    if slot.get("autoGenerated") is True or slot.get("generated") is True:
        return False
    if _text(slot.get("purpose")).lower() in {"computed", "computed_asset", "generated", "auto_generated"}:
        return False
    if slot_id in _computed_asset_slot_ids(exp_config):
        return False
    return True


def user_upload_image_slots(exp_config: Dict[str, Any]) -> List[Dict[str, Any]]:
    return [
        slot
        for slot in ((exp_config.get("inputs") or {}).get("images") or [])
        if isinstance(slot, dict) and is_user_upload_image_slot(slot, exp_config)
    ]


def required_upload_slot_ids(exp_config: Dict[str, Any]) -> List[str]:
    return [
        str(slot.get("id"))
        for slot in user_upload_image_slots(exp_config)
        if slot.get("id")
    ]


def image_slots_cover_required(image_slots: Dict[str, Any], exp_config: Dict[str, Any]) -> bool:
    required_ids = required_upload_slot_ids(exp_config)
    if not required_ids:
        return False
    for slot_id in required_ids:
        files = image_slots.get(slot_id) or []
        if not isinstance(files, list) or not any(_text(item.get("url")) for item in files if isinstance(item, dict)):
            return False
    return True


def _collect_table_node_ids(value: Any) -> set:
    node_ids = set()
    if isinstance(value, dict):
        node_id = value.get("nodeId")
        if node_id:
            node_ids.add(str(node_id))
        for child in value.values():
            node_ids.update(_collect_table_node_ids(child))
    elif isinstance(value, list):
        for child in value:
            node_ids.update(_collect_table_node_ids(child))
    return node_ids


def _table_hints(exp_config: Dict[str, Any], limit: int = 6, node_ids: Any = None) -> List[Dict[str, Any]]:
    ui = exp_config.get("ui") or {}
    tables = []
    if isinstance(ui.get("dataTables"), list):
        tables.extend(item for item in ui.get("dataTables") if isinstance(item, dict))
    if isinstance(ui.get("dataTable"), list):
        tables.extend(item for item in ui.get("dataTable") if isinstance(item, dict))
    elif isinstance(ui.get("dataTable"), dict):
        tables.append(ui.get("dataTable"))

    hints = []
    node_filter = set(str(item) for item in node_ids) if node_ids else None
    for table in tables[:limit]:
        if node_filter is not None and not (_collect_table_node_ids(table) & node_filter):
            continue
        title = ""
        for key in ["title", "caption", "name", "description"]:
            if table.get(key):
                title = _strip_unit_text(table.get(key)) or _compact(table.get(key), 30)
                break
        fields: List[str] = []
        columns = table.get("columns") or []
        if isinstance(columns, list):
            for col in columns:
                if isinstance(col, dict):
                    _append_unique(fields, col.get("text") or col.get("label"), 16)
        row_labels = table.get("rowLabels") or []
        if isinstance(row_labels, list) and row_labels:
            for item in row_labels:
                _append_unique(fields, item, 16)
        rows = table.get("rows") or []
        for row in (rows[:12] if isinstance(rows, list) else []):
            if not isinstance(row, dict):
                continue
            if row.get("label"):
                _append_unique(fields, row.get("label"), 16)
            for cell in (row.get("cells") or [])[:12]:
                if isinstance(cell, dict) and _text(cell.get("text")):
                    _append_unique(fields, cell.get("text"), 16)
        if title or fields:
            hint: Dict[str, Any] = {}
            if title:
                hint["t"] = title[:30]
            if fields:
                hint["f"] = fields
            hints.append(hint)
    return hints


def _slot_display_label(raw_label: Any, experiment_name: str, fallback: Any) -> str:
    label = _compact(raw_label, 80) or _compact(fallback, 80)
    if not label:
        return "图片槽"
    label = re.sub(r"^实验内容\s*[:：]\s*", "", label).strip()
    label = re.sub(r"签字原始数据上传", "", label).strip()
    exp_name = _compact(experiment_name, 80)
    if exp_name and label.startswith(exp_name):
        label = label[len(exp_name):].strip()
    label = re.sub(r"^\s*[-—:：]\s*", "", label).strip()
    return label or "图片槽"


def _recognition_image_ref_node_ids(exp_config: Dict[str, Any]) -> Dict[str, Any]:
    recognition = ((exp_config.get("ai") or {}).get("recognition") or {})
    refs: Dict[str, Any] = {}
    groups = recognition.get("groups") or []
    for group in groups:
        if not isinstance(group, dict) or not group.get("imageRef"):
            continue
        image_ref = str(group.get("imageRef"))
        node_ids = [str(item) for item in (group.get("nodeIds") or []) if item]
        refs.setdefault(image_ref, set()).update(node_ids)

    image_ref = recognition.get("imageRef")
    if image_ref and str(image_ref) not in refs:
        refs[str(image_ref)] = None
    return refs


def build_image_assignment_candidates(experiments: List[Any]) -> Tuple[List[Dict[str, Any]], Dict[str, Any]]:
    candidates = []
    candidate_map = {"experiments": {}, "slots": {}}
    visible_experiments = []
    for experiment in experiments:
        config = getattr(experiment, "config_json", None) or {}
        meta = config.get("meta") or {}
        enabled = meta.get("enabled", True)
        if isinstance(enabled, str):
            enabled = enabled.strip().lower() not in {"false", "0", "no", "off", "disabled"}
        if enabled is False:
            continue
        if getattr(experiment, "id", None) == OSCILLOSCOPE_EXPERIMENT_ID:
            first_slot = next(
                (
                    slot for slot in user_upload_image_slots(config)
                    if str(slot.get("id") or "") == OSCILLOSCOPE_FIRST_SLOT_ID
                ),
                None,
            )
            if first_slot:
                visible_experiments.append((experiment, config, [first_slot]))
            continue
        slots = user_upload_image_slots(config)
        if not slots:
            continue
        visible_experiments.append((experiment, config, slots))

    for exp_index, (experiment, config, slots) in enumerate(visible_experiments, start=1):
        exp_candidate_id = f"E{exp_index:02d}"
        meta = config.get("meta") or {}
        recognition_refs = _recognition_image_ref_node_ids(config)
        exp_item = {
            "candidateId": exp_candidate_id,
            "experimentId": experiment.id,
            "name": meta.get("name") or getattr(experiment, "title", "") or experiment.id,
            "slots": [],
        }
        candidate_map["experiments"][exp_candidate_id] = {
            "experiment_id": experiment.id,
            "name": exp_item["name"],
        }
        for slot_index, slot in enumerate(slots, start=1):
            slot_candidate_id = f"{exp_candidate_id}-S{slot_index:02d}"
            slot_id = str(slot.get("id") or "")
            slot_label = _slot_display_label(
                slot.get("label") or slot.get("title") or slot.get("name"),
                exp_item["name"],
                slot_id,
            )
            slot_kind = "ai_recognition" if slot_id in recognition_refs else "standalone_upload"
            slot_item = {
                "candidateId": slot_candidate_id,
                "slotId": slot_id,
                "label": slot_label,
                "kind": slot_kind,
            }
            if experiment.id == OSCILLOSCOPE_EXPERIMENT_ID and slot_id == OSCILLOSCOPE_FIRST_SLOT_ID:
                slot_item["tables"] = [OSCILLOSCOPE_FIRST_SLOT_TABLE_HINT]
            elif slot_kind == "ai_recognition":
                slot_item["tables"] = _table_hints(config, node_ids=recognition_refs.get(slot_id))
            exp_item["slots"].append({
                **slot_item,
            })
            candidate_map["slots"][slot_candidate_id] = {
                "experiment_id": experiment.id,
                "slot_id": slot_id,
                "label": slot_label,
                "kind": slot_kind,
                "experiment_candidate_id": exp_candidate_id,
            }
        candidates.append(exp_item)
    return candidates, candidate_map


def build_image_assignment_prompt(
    candidates: List[Dict[str, Any]],
    image_count: int = 0,
    image_indexes: Any = None,
) -> str:
    lines = [
        "将当前这张图片分配到一个实验图片槽。只输出槽位候选 id，不要输出解释。",
        "看不清、无法判断或不属于候选实验时返回空字符串。",
        "返回 JSON：",
        '{"slotCandidateId":"E01-S01"}',
        "候选：",
        _format_candidate_lines(candidates),
    ]
    return "\n".join(lines)


def image_assignment_reference_images(candidates: List[Dict[str, Any]]) -> List[Dict[str, str]]:
    return []
