import { useEffect, useMemo, useState } from 'react';
import { Button, Empty, Modal, Spin, Tag, message } from 'antd';
import { PlayCircleOutlined, SaveOutlined } from '@ant-design/icons';
import { AuthenticatedImage, ExperimentImageUploader } from '../experiment/ExperimentImageUploader.jsx';
import { experimentsApi } from '../../services/experimentsApi.js';
import {
  getSubmission,
  prepareSubmissionBatchForReview,
  saveSubmissionImageSlots,
} from '../../services/submissionsApi.js';
import { uploadFile } from '../../services/uploadApi.js';

const normalizeSlots = (slots = {}) => {
  const normalized = {};
  Object.entries(slots || {}).forEach(([slotId, rawItems]) => {
    const items = Array.isArray(rawItems) ? rawItems : [rawItems];
    const files = items
      .map((item) => {
        if (typeof item === 'string') return { url: item };
        return item && item.url ? item : null;
      })
      .filter(Boolean);
    if (files.length) normalized[slotId] = files;
  });
  return normalized;
};

const GENERATED_IMAGE_PURPOSES = new Set(['computed', 'computed_asset', 'generated', 'auto_generated']);

const computedAssetSlotIds = (config) => {
  const assets = config?.computedAssets || {};
  const assetItems = Array.isArray(assets) ? assets : Object.values(assets);
  return new Set(
    (assetItems || [])
      .map((asset) => asset?.imageSlotId)
      .filter(Boolean)
      .map(String)
  );
};

const isUserUploadImageSlot = (slot, config) => {
  const slotId = String(slot?.id || '');
  if (!slotId) return false;
  if (slot?.autoGenerated === true || slot?.generated === true) return false;
  if (computedAssetSlotIds(config).has(slotId)) return false;
  return !GENERATED_IMAGE_PURPOSES.has(String(slot?.purpose || '').toLowerCase());
};

const userUploadImageSlots = (config) => (
  (config?.inputs?.images || []).filter((slot) => isUserUploadImageSlot(slot, config))
);

const filterAssignmentSlots = (slots = {}, config) => {
  const allowedSlotIds = new Set(userUploadImageSlots(config).map((slot) => String(slot.id)));
  return Object.fromEntries(
    Object.entries(slots || {}).filter(([slotId]) => allowedSlotIds.has(String(slotId)))
  );
};

const buildUploadedImages = (submission) => (
  (submission?.image_paths || []).map((url, index) => ({
    uid: `${submission.id}-${index}`,
    url,
    name: `图片 ${index + 1}`,
    sourceIndex: index + 1,
  }))
);

const buildDefaultSingleSlotAssignment = (submission, config, existingSlots) => {
  if (Object.keys(existingSlots || {}).length > 0) return existingSlots;
  const imageSlots = userUploadImageSlots(config);
  if (imageSlots.length !== 1) return existingSlots;
  const uploadedImages = buildUploadedImages(submission);
  if (!uploadedImages.length) return existingSlots;
  return {
    [imageSlots[0].id]: uploadedImages,
  };
};

const AI_PREPROCESS_SUBMISSION_STATUSES = new Set([
  'preparing_review',
  'recognizing',
  'reviewing',
  'submitting',
  'draft_submitted',
  'completed',
]);

const AI_PREPROCESS_STATUSES = new Set(['queued', 'running', 'done']);

const hasEnteredAiPreprocess = (submission) => (
  AI_PREPROCESS_SUBMISSION_STATUSES.has(submission?.status)
  || AI_PREPROCESS_STATUSES.has(submission?.preprocess_status)
);

const OSCILLOSCOPE_EXPERIMENT_ID = 'exp_oscilloscope';
const OSCILLOSCOPE_LISSAJOUS_PLACEHOLDERS = {
  IMG_S6Area: '/assets/configs_images/exp_oscilloscope_img_005.png',
  IMG_S7Area: '/assets/configs_images/exp_oscilloscope_img_006.png',
  IMG_S8Area: '/assets/configs_images/exp_oscilloscope_img_007.png',
  IMG_S9Area: '/assets/configs_images/exp_oscilloscope_img_008.png',
  IMG_S10Area: '/assets/configs_images/exp_oscilloscope_img_009.png',
};

const resolveHardcodedPlaceholderImage = (experimentId, slotId) => {
  if (experimentId !== OSCILLOSCOPE_EXPERIMENT_ID) return null;
  return OSCILLOSCOPE_LISSAJOUS_PLACEHOLDERS[String(slotId)] || null;
};

export function ReviewBatchImageAssignmentModal({ open, batch, onClose, onFinished, onPrepareStarted }) {
  const [loading, setLoading] = useState(false);
  const [saving, setSaving] = useState(false);
  const [submissions, setSubmissions] = useState([]);
  const [configs, setConfigs] = useState({});
  const [activeSubmissionId, setActiveSubmissionId] = useState(null);
  const [selectedImage, setSelectedImage] = useState(null);
  const [assignments, setAssignments] = useState({});

  useEffect(() => {
    if (!open || !batch) return undefined;
    let cancelled = false;
    const load = async () => {
      setLoading(true);
      setSelectedImage(null);
      try {
        const batchExperiments = batch?.experiments || [];
        const details = await Promise.all(batchExperiments.map((exp) => getSubmission(exp.submission_id)));
        const uniqueExperimentIds = [...new Set(batchExperiments.map((exp) => exp.id))];
        const configEntries = await Promise.all(
          uniqueExperimentIds.map(async (experimentId) => [experimentId, await experimentsApi.getExperimentConfig(experimentId)])
        );
        if (cancelled) return;
        const nextConfigs = Object.fromEntries(configEntries);
        const nextAssignments = {};
        details.forEach((submission) => {
          const config = nextConfigs[submission.experiment_id];
          const existingSlots = filterAssignmentSlots(normalizeSlots(submission.image_slots), config);
          nextAssignments[submission.id] = buildDefaultSingleSlotAssignment(
            submission,
            config,
            existingSlots
          );
        });
        setSubmissions(details);
        setConfigs(nextConfigs);
        setAssignments(nextAssignments);
        setActiveSubmissionId(details[0]?.id || null);
      } catch (error) {
        if (!cancelled) message.error(error.response?.data?.detail || '加载批次图片失败');
      } finally {
        if (!cancelled) setLoading(false);
      }
    };
    load();
    return () => {
      cancelled = true;
    };
  }, [open, batch]);

  const activeSubmission = useMemo(
    () => submissions.find((submission) => submission.id === activeSubmissionId),
    [submissions, activeSubmissionId]
  );

  const activeConfig = activeSubmission ? configs[activeSubmission.experiment_id] : null;
  const imageSlots = userUploadImageSlots(activeConfig);
  const activeBatchExperiment = (batch?.experiments || []).find((item) => item.submission_id === activeSubmission?.id);
  const activeExperimentName = activeConfig?.meta?.name || activeConfig?.meta?.title || activeBatchExperiment?.name || activeSubmission?.experiment_id;
  const uploadedImages = buildUploadedImages(activeSubmission);
  const activeHasEnteredAi = hasEnteredAiPreprocess(activeSubmission);
  const preparableSubmissions = useMemo(
    () => submissions.filter((submission) => !hasEnteredAiPreprocess(submission)),
    [submissions]
  );
  const usedImageUrls = useMemo(() => {
    const urls = new Set();
    Object.values(assignments).forEach((slots) => {
      Object.values(slots || {}).forEach((items) => {
        (items || []).forEach((item) => {
          if (item?.url) urls.add(item.url);
        });
      });
    });
    return urls;
  }, [assignments]);

  const saveAssignments = async () => {
    const editableSubmissions = submissions.filter((submission) => !hasEnteredAiPreprocess(submission));
    if (!editableSubmissions.length) {
      message.info('当前批次已进入 AI 识别，无需保存图片匹配');
      return;
    }
    setSaving(true);
    try {
      await Promise.all(
        editableSubmissions.map((submission) => (
          saveSubmissionImageSlots(submission.id, assignments[submission.id] || {})
        ))
      );
      message.success('图片匹配已保存');
      onFinished?.();
    } catch (error) {
      message.error(error.response?.data?.detail || '保存图片匹配失败');
      throw error;
    } finally {
      setSaving(false);
    }
  };

  const prepareBatch = async () => {
    const nextAssignments = Object.fromEntries(
      preparableSubmissions.map((submission) => [submission.id, assignments[submission.id] || {}])
    );
    if (!Object.keys(nextAssignments).length) {
      message.info('当前批次已进入 AI 识别，无需重复提交');
      return;
    }
    setSaving(true);
    try {
      const result = await prepareSubmissionBatchForReview(batch.batch_id, nextAssignments);
      const startedCount = result?.submission_ids?.length || 0;
      const skippedCount = result?.skipped_already_processing?.length || 0;
      if (startedCount > 0) {
        message.success(skippedCount > 0 ? `已启动 ${startedCount} 个预处理，跳过 ${skippedCount} 个已进入 AI 识别的任务` : '批量预处理已启动，完成后会提示');
      } else {
        message.info('当前批次已进入 AI 识别，无需重复提交');
      }
      onPrepareStarted?.({
        batch,
        submissionIds: result?.submission_ids || [],
      });
      onFinished?.();
      onClose?.();
    } catch (error) {
      message.error(error.response?.data?.detail || '启动预处理失败');
    } finally {
      setSaving(false);
    }
  };

  const placeImageIntoSlot = (slotId, image = selectedImage) => {
    if (activeHasEnteredAi) {
      message.info('该实验已进入 AI 识别，不能再修改图片匹配');
      return;
    }
    if (!activeSubmission || !image) {
      message.warning('请先选择一张图片');
      return;
    }
    setAssignments((prev) => ({
      ...prev,
      [activeSubmission.id]: {
        ...(prev[activeSubmission.id] || {}),
        [slotId]: [image],
      },
    }));
  };

  const uploadImageIntoSlot = async (slotId, file) => {
    if (activeHasEnteredAi) {
      message.info('该实验已进入 AI 识别，不能再修改图片匹配');
      return false;
    }
    if (!activeSubmission) return false;
    message.loading({ content: '正在上传...', key: `review-upload-${file.uid || file.name}` });
    try {
      const uploaded = await uploadFile(file);
      setAssignments((prev) => ({
        ...prev,
        [activeSubmission.id]: {
          ...(prev[activeSubmission.id] || {}),
          [slotId]: [
            ...((prev[activeSubmission.id] || {})[slotId] || []),
            {
              uid: file.uid || `${slotId}-${Date.now()}`,
              name: file.name,
              url: uploaded.url,
              originFileObj: file,
            },
          ],
        },
      }));
      message.success({ content: '上传成功', key: `review-upload-${file.uid || file.name}` });
    } catch (error) {
      message.error({ content: error.message || '上传失败', key: `review-upload-${file.uid || file.name}` });
    }
    return false;
  };

  const replaceImageInSlot = async (slotId, uidToReplace, file) => {
    if (activeHasEnteredAi) {
      message.info('该实验已进入 AI 识别，不能再修改图片匹配');
      return false;
    }
    if (!activeSubmission) return false;
    message.loading({ content: '正在旋转并上传...', key: `review-rotate-${uidToReplace}` });
    try {
      const uploaded = await uploadFile(file);
      setAssignments((prev) => ({
        ...prev,
        [activeSubmission.id]: {
          ...(prev[activeSubmission.id] || {}),
          [slotId]: ((prev[activeSubmission.id] || {})[slotId] || []).map((item) => (
            item.uid === uidToReplace
              ? { ...item, name: file.name, url: uploaded.url, originFileObj: file }
              : item
          )),
        },
      }));
      message.success({ content: '图片已旋转并保存', key: `review-rotate-${uidToReplace}` });
      return true;
    } catch (error) {
      message.error({ content: error.message || '旋转失败', key: `review-rotate-${uidToReplace}` });
      return false;
    }
  };

  const removeSlotImage = (slotId) => {
    if (activeHasEnteredAi) {
      message.info('该实验已进入 AI 识别，不能再修改图片匹配');
      return;
    }
    if (!activeSubmission) return;
    setAssignments((prev) => {
      const nextSlots = { ...(prev[activeSubmission.id] || {}) };
      delete nextSlots[slotId];
      return { ...prev, [activeSubmission.id]: nextSlots };
    });
  };

  return (
    <Modal
      rootClassName="pro-submit-modal-root"
      className="pro-submit-fullscreen-modal review-image-match-modal"
      title={
        <div className="pro-submit-modal-title">
          <span>图片匹配与批量预处理</span>
        </div>
      }
      open={open}
      width="100vw"
      onCancel={onClose}
      footer={[
        <Button key="cancel" onClick={onClose}>取消</Button>,
        <Button key="save" icon={<SaveOutlined />} loading={saving} onClick={saveAssignments}>保存草稿</Button>,
        <Button
          key="prepare"
          type="primary"
          icon={<PlayCircleOutlined />}
          loading={saving}
          disabled={!preparableSubmissions.length}
          onClick={prepareBatch}
        >
          确认匹配并开始处理
        </Button>,
      ]}
      destroyOnClose
    >
      {loading ? (
        <div style={{ height: 420, display: 'grid', placeItems: 'center' }}>
          <Spin />
        </div>
      ) : (
        <div className="review-batch-assignment">
          <aside className="review-batch-assignment-list">
            {submissions.map((submission) => {
              const exp = (batch?.experiments || []).find((item) => item.submission_id === submission.id);
              const slotCount = Object.values(assignments[submission.id] || {}).reduce((sum, items) => sum + items.length, 0);
              const enteredAi = hasEnteredAiPreprocess(submission);
              return (
                <button
                  key={submission.id}
                  type="button"
                  className={`review-batch-assignment-item ${submission.id === activeSubmissionId ? 'is-active' : ''}`}
                  onClick={() => {
                    setActiveSubmissionId(submission.id);
                    setSelectedImage(null);
                  }}
                >
                  <span>{exp?.name || submission.experiment_id}</span>
                  {enteredAi ? (
                    <Tag color="purple">已进入AI识别</Tag>
                  ) : (
                    <Tag color={slotCount > 0 ? 'green' : 'default'}>{slotCount > 0 ? '已匹配' : '未匹配'}</Tag>
                  )}
                </button>
              );
            })}
          </aside>
          <section className="review-batch-assignment-workspace">
            <div className="review-batch-image-pool">
              <div className="review-batch-panel-title">学生上传图片</div>
              {uploadedImages.length ? uploadedImages.map((image) => (
                <button
                  key={image.uid}
                  type="button"
                  className={`review-batch-image-thumb ${selectedImage?.url === image.url ? 'is-selected' : ''}`}
                  onClick={() => setSelectedImage(image)}
                  draggable
                  onDragStart={(event) => {
                    const payload = JSON.stringify(image);
                    event.dataTransfer.effectAllowed = 'copy';
                    event.dataTransfer.setData('application/json', payload);
                    event.dataTransfer.setData('text/plain', payload);
                  }}
                >
                  <AuthenticatedImage src={image.url} alt={image.name || 'uploaded'} />
                  <span>{image.name}</span>
                  {usedImageUrls.has(image.url) && <Tag color="green">已使用</Tag>}
                </button>
              )) : <Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="暂无图片" />}
            </div>
            <div className="review-batch-slot-panel">
              {activeHasEnteredAi && (
                <div className="review-batch-ai-status">该实验已进入 AI 识别，图片匹配已锁定。</div>
              )}
              {imageSlots.length ? (
                <div className="review-batch-slot-stack">
                  {imageSlots.map((slot) => {
                    const title = slot.title || slot.label || slot.id;
                    const uploaderTitle = activeExperimentName ? `${activeExperimentName} - ${title}` : title;
                    return (
                      <ExperimentImageUploader
                        key={slot.id}
                        images={[slot]}
                        imageSlots={assignments[activeSubmission?.id] || {}}
                        onImageUpload={uploadImageIntoSlot}
                        onImageReplace={replaceImageInSlot}
                        onExternalImageDrop={placeImageIntoSlot}
                        onRemoveImage={removeSlotImage}
                        recognitionDef={null}
                        title={uploaderTitle}
                        emptyTitle="拖动左侧图片到这里"
                        emptyHint="支持预览、缩放、旋转和移除。"
                        className="is-inline-image-node review-batch-slot-uploader"
                        placeholderImage={resolveHardcodedPlaceholderImage(activeSubmission?.experiment_id, slot.id)}
                      />
                    );
                  })}
                </div>
              ) : <Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="该实验未配置图片槽" />}
            </div>
          </section>
        </div>
      )}
    </Modal>
  );
}
