"""add submitted_by

Revision ID: 84be32c4904f
Revises: 27ff1475f5fd
Create Date: 2026-07-01 10:37:06.306941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '84be32c4904f'
down_revision: Union[str, Sequence[str], None] = '27ff1475f5fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('submitted_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'submissions', 'users', ['submitted_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('submissions_submitted_by_fkey', 'submissions', type_='foreignkey')
    op.drop_column('submissions', 'submitted_by')
    # ### end Alembic commands ###
