"""seed_upgrade_plan

Revision ID: a9db03851265
Revises: ad699cef962c
Create Date: 2026-07-01 12:58:17.839602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a9db03851265'
down_revision: Union[str, Sequence[str], None] = 'ad699cef962c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("INSERT INTO experiments (id, title, version, config_json, mapping_json, created_at) VALUES ('UPGRADE_PLAN', '系统套餐升级', '1.0', '{}', '{}', NOW()) ON CONFLICT (id) DO NOTHING;")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM experiments WHERE id = 'UPGRADE_PLAN';")
    # ### end Alembic commands ###
