"""add_ai_tables

Revision ID: c8ce0acca9cc
Revises: 88bb3a1acbd7
Create Date: 2026-07-02 04:42:53.456051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c8ce0acca9cc'
down_revision: Union[str, Sequence[str], None] = '88bb3a1acbd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fallback_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('api_key_encrypted', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('max_images_per_task', sa.Integer(), nullable=False),
    sa.Column('max_concurrent_tasks', sa.Integer(), nullable=False),
    sa.Column('auto_recognize', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_prompt_templates',
    sa.Column('experiment_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('recognition_system_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('recognition_extra_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('generation_system_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('generation_extra_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('experiment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_prompt_templates')
    op.drop_table('ai_config')
    # ### end Alembic commands ###
